builds:
  -
    id: "daylight"
    binary: daylight
    main: ./cmd/daylight/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 7
archives:
  -
    id: daylight-binaries
    name_template: "daylight-{{ .Os }}_{{ .Arch }}_{{ .Version }}"
    files:
      - LICENSE
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
nfpms:
  -
    file_name_template: "daylight_package_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: Michael Paepcke
    homepage: https://paepcke.de/daylight
    maintainer: Michael Paepcke <git@paepcke.de>
    description: daylight
    license: BSD 3-Clause
    formats:
      - deb
      - rpm
